name: latihan_modul_6
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  build_runner: ^2.4.7
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.6.6
  http: ^0.13.3
  mockito: ^5.4.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
